name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./registration/pom.xml
          mvn clean package -f ./gosuclass/pom.xml
          mvn clean package -f ./evaluation/pom.xml
          mvn clean package -f ./history/pom.xml
          mvn clean package -f ./recommend/pom.xml

      - name: Docker Build and push for Registration
        uses: docker/build-push-action@v4
        with:
          context: ./registration
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/registration:latest
            ghcr.io/${{ github.repository }}/registration:${{ github.ref_name }}
            
      - name: Docker Build and push for Gosuclass
        uses: docker/build-push-action@v4
        with:
          context: ./gosuclass
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/gosuclass:latest
            ghcr.io/${{ github.repository }}/gosuclass:${{ github.ref_name }}
            
      - name: Docker Build and push for Evaluation
        uses: docker/build-push-action@v4
        with:
          context: ./evaluation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/evaluation:latest
            ghcr.io/${{ github.repository }}/evaluation:${{ github.ref_name }}
            
      - name: Docker Build and push for History
        uses: docker/build-push-action@v4
        with:
          context: ./history
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/history:latest
            ghcr.io/${{ github.repository }}/history:${{ github.ref_name }}
            
      - name: Docker Build and push for Recommend
        uses: docker/build-push-action@v4
        with:
          context: ./recommend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/recommend:latest
            ghcr.io/${{ github.repository }}/recommend:${{ github.ref_name }}
            
