apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosuclass
  labels:
    app: gosuclass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosuclass
  template:
    metadata:
      labels:
        app: gosuclass
    spec:
      containers:
        - name: gosuclass
          image: "username/gosuclass:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
